In [1]:
import numpy as np

In [2]:
# If numpy if not installed Then install by "!pip3 install numpy"

In [3]:
list=[1,2,3,4] #List in Python 
print(list,type(list))

[1, 2, 3, 4] <class 'list'>


In [4]:
array=np.array(list) #Converting Python List to Numpy array

In [5]:
print(array,type(array))

[1 2 3 4] <class 'numpy.ndarray'>


In [6]:
ar=np.array([1,2,3,0.0000000000000000000000000000000000000000000000000000000000000000000004444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444444])

In [7]:
print(ar,type(ar),ar.dtype,ar.ndim)

[1.00000000e+00 2.00000000e+00 3.00000000e+00 4.44444444e-70] <class 'numpy.ndarray'> float64 1


In [8]:
print(ar.shape) # size

(4,)


In [9]:
ar2d=np.array([[1,23,4],[2,3,4],[3,4,5]])
print(ar2d,type(ar2d),ar2d.dtype,ar2d.shape)

[[ 1 23  4]
 [ 2  3  4]
 [ 3  4  5]] <class 'numpy.ndarray'> int64 (3, 3)


In [10]:
arr=np.zeros((2,3),dtype="int64")
print(arr,arr.dtype,arr.ndim)

[[0 0 0]
 [0 0 0]] int64 2


In [11]:
arr=np.ones((3,5),dtype="int64")
print(arr,arr.dtype)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] int64


In [12]:
arr=np.full((5,3),24,dtype="int64")
print(arr,type(arr),arr.shape)

[[24 24 24]
 [24 24 24]
 [24 24 24]
 [24 24 24]
 [24 24 24]] <class 'numpy.ndarray'> (5, 3)


In [13]:
arr=np.eye((5),dtype="int64")
print(arr ,arr.shape)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]] (5, 5)


In [21]:
arr=np.eye(5,3,dtype="int64")
print(arr ,arr.shape,arr.ndim)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 0 0]
 [0 0 0]] (5, 3) 2


In [31]:
# vectorization

arr=np.array([1,2,3,4,5],dtype="int64")
arr2=np.array([6,7,8,9,10])
print(arr+arr2)
print(arr**arr2)
print(arr+1)

[ 7  9 11 13 15]
[      1     128    6561  262144 9765625]
[2 3 4 5 6]


In [27]:
#Usage of Numpy Broadcasting -- Std Normalization(z-score)

arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
print(f"mean = {mean}")
std_deviation=np.std(arr)
print(f"standard deviation = {std_deviation}")
normalized_arr=(arr-mean)/std_deviation
print(normalized_arr)

mean = 2.5
standard deviation = 1.118033988749895
[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
